### PR TITLE
Huggingface Gradio Demo

### PR DESCRIPTION
**Pull request by AK391**
easy to use web demo on huggingface spaces using gradio

### CODE REVIEW

**Comment by lucabeetz** [comment]
Your demo is great and easy to use, I just made a Colab which also generates a GIF from the individual images but the gradio demo is nicer

https://colab.research.google.com/drive/1m2gAYOdRIQVxrnVySmA-Pug0H_I13-Sp?usp=sharing

**Comment by AK391** [comment]
@lucabeetz thanks the colab says access denied

**Comment by lucabeetz** [comment]
Oh yeah, sorry. I have updated the link

**Comment by AK391** [comment]
@lucabeetz nice work the demo on HF now outputs a gif as well

**Comment by Huage001** [comment]
Thank you for your nice interactive demo!

**Pull request merged**
